/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary': '#00363a',
        'inverse-on-surface': '#2b3138',
        secondary: '#dcb8ff',
        'on-surface-variant': '#b9cacb',
        'error-container': '#93000a',
        'surface-bright': '#343a41',
        'primary-container': '#00f0ff',
        'on-surface': '#dde3ec',
        error: '#ffb4ab',
        'surface-container-low': '#161c23',
        'tertiary-fixed': '#ffdbd0',
        'secondary-fixed-dim': '#dcb8ff',
        'on-tertiary-container': '#af3200',
        'surface-variant': '#2f353c',
        'tertiary-fixed-dim': '#ffb59e',
        'on-background': '#dde3ec',
        'primary-fixed': '#7df4ff',
        'on-error': '#690005',
        'secondary-container': '#7701d0',
        'tertiary-container': '#ffcfc1',
        'surface-container': '#1a2027',
        primary: '#dbfcff',
        'secondary-fixed': '#efdbff',
        'outline-variant': '#3b494b',
        'on-primary-fixed': '#002022',
        'on-tertiary-fixed-variant': '#852400',
        background: '#0e141a',
        'surface-container-highest': '#2f353c',
        tertiary: '#fff4f1',
        'inverse-surface': '#dde3ec',
        'on-secondary-fixed': '#2c0051',
        'on-error-container': '#ffdad6',
        'on-secondary': '#480081',
        surface: '#0e141a',
        'surface-container-high': '#252a31',
        'inverse-primary': '#006970',
        'on-secondary-fixed-variant': '#6700b5',
        'primary-fixed-dim': '#00dbe9',
        'on-tertiary': '#5e1700',
        'on-primary-container': '#006970',
        'surface-container-lowest': '#090f15',
        'surface-dim': '#0e141a',
        outline: '#849495',
        'on-tertiary-fixed': '#3a0b00',
        'surface-tint': '#00dbe9',
        'on-primary-fixed-variant': '#004f54',
        'on-secondary-container': '#dcb7ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        grotesk: ['Space Grotesk', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
